# Generated by Django 5.1.7 on 2025-04-08 12:11

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineModels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('period', models.IntegerField(blank=True, help_text='例：7 = 毎週、30 = 毎月', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='周期')),
                ('start_date', models.TimeField(default=datetime.date.today, verbose_name='開始日時')),
                ('create_at', models.TimeField(auto_now_add=True, verbose_name='作成日時')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('notice_text', models.TextField(max_length=1000, verbose_name='通知内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
