# Generated by Django 5.1.7 on 2025-04-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_remove_routinemodels_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routinemodels',
            name='start_date',
        ),
    ]
