# Generated by Django 5.1.7 on 2025-04-11 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_remove_routinemodels_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinemodels',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='開始日時'),
        ),
    ]
